### ISSUE TITLE
It works whit newest version of PMMP?

### ISSUE THREAD

**Issue by LewBr** [GoMint/ProxProx#19]
Hey, it works to transfer faster a player to another server faster whit PMMP? and how can i do this exactly?

**Comment by chaosfreak93** [comment]
Yes

**Comment by LewBr** [comment]
how can i configure that in pocketmine?

**Comment by LewBr** [comment]
or install

**Comment by LordThePeaz** [comment]
I have this problem too

**Comment by GamerDaniel3000** [comment]
Now it works with the newst commit!

**Comment by LewBr** [comment]
Have you tested?

**Comment by Shad0wCore** [comment]
https://github.com/GoMint/ProxProx/commit/91a9e73df2ce5ee0b3133fd606eb81925f532a2d

**Comment by Shad0wCore** [comment]
Issue conversation is locked now due to the fact that the issue was solved a long time ago by a commit (see my latest post in this conversation).

#Closed
