### ISSUE TITLE
How do I setup ProxProx?

### ISSUE THREAD

**Issue by Emis02** [GoMint/ProxProx#38]
whit what version work?

**Comment by Shad0wCore** [comment]
What do you mean?

**Comment by Emis02** [comment]
What version of mcpe

**Comment by Shad0wCore** [comment]
![image](https://user-images.githubusercontent.com/17110757/49344352-358ff200-f676-11e8-9eab-61e789437573.png)
Currently MCPE version `1.7.0`

**Comment by Emis02** [comment]
But transfer not work

**Comment by Shad0wCore** [comment]
What do you mean exactly? Transfer between servers?

**Comment by Emis02** [comment]
How work?

**Comment by Shad0wCore** [comment]
I'm currently having troubles understanding you. If you're not a native English speaker I encourage you to use deepl.com or Google Translate to translate your text to English so I can understand you better.

**Comment by Emis02** [comment]
How work this work?

**Comment by Shad0wCore** [comment]
Do you speak English?
Sprichst du Deutsch?
¿Hablas español?
Parli italiano?
Vous parlez français ?
Spreekt u Nederlands?
Czy mówisz po polsku?

**Comment by Emis02** [comment]
Parlo italiano

**Comment by Shad0wCore** [comment]
Descrivi il tuo problema nella tua lingua e io lo tradurrò per gli altri. Io uso un traduttore. Quindi, se ci sono errori grammaticali o qualcosa del genere, sai perché.

> Translation: Just describe your problem in your language and I will translate it for others. I use a translator. So if there are grammatical mistakes or something like that, you know why.

**Comment by Emis02** [comment]
Non so usare questo plugin, lo metto nei plugin di gomint e poi come si avvia il fast transfer verso altri server?

**Comment by Shad0wCore** [comment]
Quale plugin vuoi dire?

> Translation: Which plugin do you mean?

**Comment by Emis02** [comment]
Proxprox

**Comment by Shad0wCore** [comment]
"ProxProx" non è un plugin per "GoMint". Si tratta di un proxy per inviare i giocatori avanti e indietro tra i server.
> Translation: "ProxProx" is not a plugin for "GoMint". It is a proxy to send players back and forth between servers.

**Comment by Emis02** [comment]
Come si utilizza?

**Comment by Shad0wCore** [comment]
Conoscete "BungeeCord"? È fondamentalmente uguale a "BungeeCord" ma per Minecraft PE. Puoi leggere le funzionalità di un proxy qui: https://wiki.nitrado.net/en/BungeeCord

> Translation: Do you know "BungeeCord"? It is basically the same as "BungeeCord" but for Minecraft PE. You can read about the functionality of a proxy here: https://wiki.nitrado.net/en/BungeeCord

**Comment by Emis02** [comment]
Come si avvia?

**Comment by Shad0wCore** [comment]
È possibile impostare "ProxProx" esattamente come "BungeeCord". Cerca i tutorial su YouTube su come impostare "BungeeCord".
> Translation: You setup "ProxProx" the exact same way like "BungeeCord". Search for tutorials on YouTube how to setup "BungeeCord".

**Comment by Emis02** [comment]
Dove trovo il file jar?

**Comment by lukeeey** [comment]
@Shad0wCore Are you manually editing those messages to include the translations or using a bit?

**Comment by Shad0wCore** [comment]
@lukeeey I'm actually manually translating and editing the messages

**Comment by lukeeey** [comment]
@Shad0wCore Are you manually adding translations or using a bot?

**Comment by DelxHQ** [comment]
Yes

**Comment by Shad0wCore** [comment]
@lukeeey Everything's done manually. There's no automation.

**Comment by lukeeey** [comment]
I'd like to make a bot for it at some point

**Comment by Shad0wCore** [comment]
@lukeeey Use deepl.com for it. Thank you.

**Comment by Shad0wCore** [comment]
Si prega di chiudere il problema se la tua domanda ha ricevuto risposta.
> Translation: Please close the issue if your question was answered

**Comment by Emis02** [comment]
Funziona il trasferimento verso pmmp?

**Comment by Shad0wCore** [comment]
Dovrebbe funzionare senza problemi.
> Translation: It should work without any problems.

**Comment by Emis02** [comment]
Connection - Connected to 127.0.0.1:19132
20:06:26.945 [main] INFO  io.gomint.proxprox.network.DownstreamConnection - Player io.gomint.proxprox.network.UpstreamConnection@5d1acc7a disconnected from server io.gomint.proxprox.network.DownstreamConnection@b01b2c24: disconnectionScreen.notAuthenticated
20:06:29.843 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 1 | ACK: 0 | NAK: 5 | RTT: 0
20:06:30.845 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 1 | ACK: 0 | NAK: 6 | RTT: 0
20:06:31.851 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 2 | ACK: 0 | NAK: 10 | RTT: 0
20:06:32.855 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 2 | ACK: 0 | NAK: 12 | RTT: 0
20:06:33.859 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 3 | ACK: 0 | NAK: 15 | RTT: 0
20:06:34.866 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 4 | ACK: 0 | NAK: 18 | RTT: 0
20:06:35.873 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 4 | ACK: 0 | NAK: 21 | RTT: 0
20:06:36.874 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 5 | ACK: 0 | NAK: 23 | RTT: 0
20:06:36.948 [jRaknet Ticker] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnected downstream...

**Comment by Shad0wCore** [comment]
In realta' non so cosa significhi questo. Penso che @geNAZt sia meglio di rispondere a questo.
> Translation: I actually don't know what this means. I think @geNAZt is better of with answering this.

**Comment by Emis02** [comment]
quindi?
