### ISSUE TITLE
Could not connect to PMMP server

### ISSUE THREAD

**Issue by GamakCZ** [GoMint/ProxProx#57]
**Describe the bug**
I can not connect to pmmp server

**To Reproduce**
1. Start pmmp server on some hosting like fakaheda.eu
2. Start proxprox on localhost
3. Join proxprox server

**Expected behavior**
Connect to the pmmp server

**Screenshots**

In mc I can see this
![image](https://user-images.githubusercontent.com/17053298/50734974-8fb93100-11a7-11e9-9563-d48a3666f9be.png)

** PMMP Server:
- OS: linux
- php: 7.2
- log: [11:36:14] [Server thread/INFO]: VixikCZ[/*.*.*.*:54836] logged out due to You need to authenticate to Xbox Live.

**ProxProx (please complete the following information):**
 - OS: win
 - Version 10

**Additional context**
`D:\Projekty\ProxProx>java -jar ProxProx.jar
11:42:19.792 [main] INFO  io.gomint.proxprox.ProxProxProxy - Starting ProxProxProxy v1.0.0
11:42:20.526 [main] INFO  io.gomint.proxprox.ProxProxProxy - Bound to 0.0.0.0:19132
11:42:29.916 [nioEventLoopGroup-2-1] INFO  jRaknet - Fully established new incoming connection: /192.168.10.107:59550
11:42:29.995 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Login version number: 313
11:42:30.088 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: ***
11:42:30.088 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: ***
11:42:30.088 [main] INFO  io.gomint.proxprox.jwt.MojangChainValidator - Provided trusted key: ***
11:42:30.088 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Got valid XBOX Live Account ID: ***
11:42:30.104 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Logged in as VixikCZ (UUID: ***; GUID: ***)
11:42:30.385 [main] INFO  io.gomint.proxprox.network.UpstreamConnection - Crafted JWT for client: ***
11:42:31.416 [nioEventLoopGroup-2-3] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to *.*.*.*:27994
11:42:31.853 [main] INFO  io.gomint.proxprox.network.DownstreamConnection - Player io.gomint.proxprox.network.UpstreamConnection@aa1d4b7a disconnected from server io.gomint.proxprox.network.DownstreamConnection@1210755a: disconnectionScreen.notAuthenticated
11:42:34.446 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 1 | ACK: 0 | NAK: 1 | RTT: 0
11:42:35.448 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 2 | ACK: 0 | NAK: 1 | RTT: 0
11:42:36.464 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 2 | ACK: 0 | NAK: 3 | RTT: 0
11:42:37.479 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 3 | ACK: 0 | NAK: 2 | RTT: 0
11:42:38.494 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 3 | ACK: 0 | NAK: 4 | RTT: 0
11:42:39.509 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 4 | ACK: 0 | NAK: 4 | RTT: 0
11:42:40.510 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 4 | ACK: 0 | NAK: 5 | RTT: 0
11:42:41.526 [jRaknet Ticker] WARN  io.gomint.jraknet.ClientSocket - Packet loss detected: 100,000% | Resend queue: 5 | ACK: 0 | NAK: 6 | RTT: 0
11:42:41.854 [jRaknet Ticker] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnected downstream...`

**Comment by GamakCZ** [comment]
when I disable xbox auth on pmmp server it works well

**Comment by geNAZt** [comment]
You need to disable xbox auth, proxprox downstream connections are never authed against xbox
